# %%
import numpy as np
import glob, os
# %%
ls = glob.glob('./*.png')
ls
# %%
image("Figures/bmUnivariate/timing_with_stats_2'-fucosyllactose.png",)
image("Figures/bmUnivariate/timing_with_stats_3'-sialyllactose.png",)
image("Figures/bmUnivariate/timing_with_stats_3-fucosyllactose.png",)
image("Figures/bmUnivariate/timing_with_stats_6'-sialyllactose.png",)
image("Figures/bmUnivariate/timing_with_stats_Fucose.png",)
image("Figures/bmUnivariate/timing_with_stats_Galactose.png",)
image("Figures/bmUnivariate/timing_with_stats_Glucose.png",)
image("Figures/bmUnivariate/timing_with_stats_Lactose.png",)

image("Figures/bmUnivariate/timing_with_stats_2-Aminobutyrate.png",)
image("Figures/bmUnivariate/timing_with_stats_Alanine.png",)
image("Figures/bmUnivariate/timing_with_stats_Asparagine.png",)
image("Figures/bmUnivariate/timing_with_stats_Aspartate.png",)
image("Figures/bmUnivariate/timing_with_stats_Betaine.png",)
image("Figures/bmUnivariate/timing_with_stats_Glutamate.png",)
image("Figures/bmUnivariate/timing_with_stats_Glutamine.png",)
image("Figures/bmUnivariate/timing_with_stats_Glycine.png",)
image("Figures/bmUnivariate/timing_with_stats_Histidine.png",)
image("Figures/bmUnivariate/timing_with_stats_Isoleucine.png",)
image("Figures/bmUnivariate/timing_with_stats_Leucine.png",)
image("Figures/bmUnivariate/timing_with_stats_Lysine.png",)
image("Figures/bmUnivariate/timing_with_stats_Methionine.png",)
image("Figures/bmUnivariate/timing_with_stats_Phenylalanine.png",)
image("Figures/bmUnivariate/timing_with_stats_Proline.png",)
image("Figures/bmUnivariate/timing_with_stats_Taurine.png",)
image("Figures/bmUnivariate/timing_with_stats_Threonine.png",)
image("Figures/bmUnivariate/timing_with_stats_Tryptophan.png",)
image("Figures/bmUnivariate/timing_with_stats_Tyrosine.png",)
image("Figures/bmUnivariate/timing_with_stats_Urea.png",)
image("Figures/bmUnivariate/timing_with_stats_Valine.png",)

image("Figures/bmUnivariate/timing_with_stats_2-Oxoglutarate.png",)
image("Figures/bmUnivariate/timing_with_stats_Acetone.png",)
image("Figures/bmUnivariate/timing_with_stats_cis-Aconitate.png",)
image("Figures/bmUnivariate/timing_with_stats_Citrate.png",)
image("Figures/bmUnivariate/timing_with_stats_Creatine phosphate.png",)
image("Figures/bmUnivariate/timing_with_stats_Creatine.png",)
image("Figures/bmUnivariate/timing_with_stats_Creatinine.png",)
image("Figures/bmUnivariate/timing_with_stats_Fumarate.png",)
image("Figures/bmUnivariate/timing_with_stats_Lactate.png",)
image("Figures/bmUnivariate/timing_with_stats_Pyruvate.png",)
image("Figures/bmUnivariate/timing_with_stats_Succinate.png",)

image("Figures/bmUnivariate/timing_with_stats_Acetate.png",)
image("Figures/bmUnivariate/timing_with_stats_Butyrate.png",)
image("Figures/bmUnivariate/timing_with_stats_Caprate.png",)
image("Figures/bmUnivariate/timing_with_stats_Caprylate.png",)
image("Figures/bmUnivariate/timing_with_stats_Choline.png",)
image("Figures/bmUnivariate/timing_with_stats_Ethanolamine.png",)
image("Figures/bmUnivariate/timing_with_stats_Methanol.png",)
image("Figures/bmUnivariate/timing_with_stats_myo-Inositol.png",)
image("Figures/bmUnivariate/timing_with_stats_O-Phosphocholine.png",)
image("Figures/bmUnivariate/timing_with_stats_sn-Glycero-3-phosphocholine.png",)
image("Figures/bmUnivariate/timing_with_stats_Uridine.png",)
